import { DefaultTokens } from "@openfun/cunningham-tokens";

export const tokens = (defaults: DefaultTokens) => ({
  "background-color": defaults.contextuals.background.surface.primary,
  "border-color": defaults.contextuals.border.neutral.tertiary,
  "border-radius": "0.5rem",
  "border-width": "2px",
  "border-style": "dotted",
  "background-color--active": defaults.contextuals.background.brand.tertiary,
  color: defaults.contextuals.content.neutral.primary,
  "color--success": defaults.contextuals.content.success.tertiary,
  "color--error": defaults.contextuals.content.error.tertiary,
  padding: "1rem",
  "accent-color": defaults.contextuals.border.brand.primary,
  "text-color": defaults.contextuals.content.neutral.tertiary,
  "text-size": "0.6875rem",
  "file-text-size": "0.8125rem",
  "file-text-color": defaults.contextuals.content.neutral.primary,
  "file-text-weight": defaults.globals.font.weights.light,
  "file-border-color": defaults.contextuals.border.neutral.tertiary,
  "file-border-width": "1px",
  "file-border-radius": "0.5rem",
  "file-background-color": defaults.contextuals.background.surface.primary,
  "file-specs-size": "0.6875rem",
  "file-specs-color": defaults.contextuals.content.neutral.tertiary,
});
