import { Configuration } from "@openfun/cunningham-react";

const defaultConfig: Configuration = {
  themes: {
    redflux_dark: {
      theme: {
        colors: {
          "primary-text": "#FFFFFF",
          "primary-100": "#FA8D92",
          "primary-200": "#F95B63",
          "primary-300": "#F72A35",
          "primary-400": "#E50914",
          "primary-500": "#C30811",
          "primary-600": "#A0060E",
          "primary-700": "#7E050B",
          "primary-800": "#5C0408",
          "primary-900": "#390205",
          "secondary-text": "#FFF",
          "secondary-100": "#1b5ad7",
          "secondary-200": "#146cea",
          "secondary-300": "#007ffe",
          "secondary-400": "#008eff",
          "secondary-500": "#279eff",
          "secondary-600": "#56b0ff",
          "secondary-700": "#8ac6ff",
          "secondary-800": "#b9dcff",
          "secondary-900": "#e2f1ff",
          "greyscale-000": "#000000BB",
          "greyscale-100": "#191919BB",
          "greyscale-200": "#232323",
          "greyscale-300": "#292929",
          "greyscale-400": "#343434",
          "greyscale-500": "#404040",
          "greyscale-600": "#aaaaaa",
          "greyscale-700": "#cccccc",
          "greyscale-800": "#eeeeee",
          "greyscale-900": "#f7f7f7",
          "danger-900": "#FACED0",
          "danger-800": "#F7A9AD",
          "danger-700": "#F38389",
          "danger-600": "#F05E66",
          "danger-500": "#EC3942",
          "danger-400": "#D8151F",
          "danger-300": "#A51017",
          "danger-200": "#720B10",
          "danger-100": "#3F0609",
          "info-900": "#53A4FD",
          "info-800": "#2B8FFC",
          "info-700": "#047AFA",
          "info-600": "#0366D2",
          "info-500": "#0255AF",
          "info-400": "#02448C",
          "info-300": "#013368",
          "info-200": "#012245",
          "info-100": "#001122",
          "success-900": "#A9F7C0",
          "success-800": "#8DF4AC",
          "success-700": "#71F198",
          "success-600": "#55EF83",
          "success-500": "#39EC6F",
          "success-400": "#14CF4C",
          "success-300": "#0E9236",
          "success-200": "#085620",
          "success-100": "#021909",
          "warning-900": "#EAC88B",
          "warning-800": "#E4BA6D",
          "warning-700": "#DFAB4F",
          "warning-600": "#D99D31",
          "warning-500": "#B68121",
          "warning-400": "#8A621A",
          "warning-300": "#5F4412",
          "warning-200": "#34250A",
          "warning-100": "#090702",
        },
        font: {
          families: {
            base: "Helvetica Neue,Segoe UI,Roboto,Ubuntu,sans-serif",
            accent: "Helvetica Neue,Segoe UI,Roboto,Ubuntu,sans-serif",
          },
        },
      },
      components: {
        button: {
          "border-radius": "0.1875rem",
        },
        "forms-input": {
          "border-radius": "0.1875rem",
          "border-color": "ref(theme.colors.greyscale-500)",
          "border-color--hover": "ref(theme.colors.greyscale-600)",
          "background-color": "ref(theme.colors.greyscale-100)",
          "label-color--focus": "ref(theme.colors.greyscale-700)",
        },
        "forms-select": {
          "border-radius": "0.1875rem",
          "border-color": "ref(theme.colors.greyscale-500)",
          "border-color--hover": "ref(theme.colors.greyscale-600)",
          "background-color": "ref(theme.colors.greyscale-100)",
          "border-color--focus": "ref(theme.colors.greyscale-700)",
          "label-color--focus": "ref(theme.colors.greyscale-700)",
          "menu-background-color": "#191919",
          "item-background-color--selected": "ref(theme.colors.primary-600)",
        },
        "forms-datepicker": {
          "border-radius": "0.1875rem",
          "border-color": "ref(theme.colors.greyscale-500)",
          "border-color--hover": "ref(theme.colors.greyscale-600)",
          "background-color": "ref(theme.colors.greyscale-100)",
          "border-color--focus": "ref(theme.colors.greyscale-700)",
          "label-color--focus": "ref(theme.colors.greyscale-700)",
          "menu-background-color": "#191919",
          "grid-cell--border-color--today": "ref(theme.colors.greyscale-800)",
          "grid-cell--color--today": "ref(theme.colors.greyscale-800)",
          "range-selection-background-color": "ref(theme.colors.primary-900)",
          "item-background-color--selected": "ref(theme.colors.primary-600)",
        },
        "forms-fileuploader": {
          "border-color": "ref(theme.colors.greyscale-500)",
          "border-color--hover": "ref(theme.colors.greyscale-600)",
          "background-color": "ref(theme.colors.greyscale-100)",
          "background-color--active": "ref(theme.colors.greyscale-500)",
          "accent-color": "ref(theme.colors.greyscale-800)",
        },
        "forms-textarea": {
          "border-radius": "0.1875rem",
          "border-color": "ref(theme.colors.greyscale-500)",
          "border-color--hover": "ref(theme.colors.greyscale-600)",
          "background-color": "ref(theme.colors.greyscale-100)",
          "border-color--focus": "ref(theme.colors.greyscale-700)",
          "label-color--focus": "ref(theme.colors.greyscale-700)",
        },
        "forms-checkbox": {
          "border-radius": "0.1875rem",
          "accent-color": "ref(theme.colors.greyscale-100)",
          "background-color": "ref(theme.colors.greyscale-800)",
        },
        "forms-switch": {
          "handle-border-radius": "0.3rem",
          "rail-border-radius": "0.500rem",
          "accent-color": "ref(theme.colors.greyscale-800)",
          "handle-background-color": "ref(theme.colors.greyscale-100)",
          "rail-background-color": "ref(theme.colors.greyscale-400)",
        },
        "forms-radio": {
          "accent-color": "ref(theme.colors.greyscale-100)",
          "background-color": "ref(theme.colors.greyscale-800)",
        },
        modal: {
          "border-radius": "0.1875rem",
          "background-color": "#191919",
        },
        card: {
          "border-radius": "0.1875rem",
          "border-width": "none",
          "box-shadow": "rgba(255, 220, 220, 0.05) 0px 0px 60px 10px",
        },
      },
    },
  },
};

export default defaultConfig;
